 chmod -x ".chezmoi.sourceignore"
 chmod -x ".chezmoidata.yaml"
 chmod -x ".chezmoiignore"
 chmod -x ".chezmoiremove"
 chmod -x ".chezmoiroot"
 chmod -x ".chezmoiversion"
 chmod -x ".devcontainer/Dockerfile"
 chmod -x ".devcontainer/Makefile"
 chmod -x ".devcontainer/README.md"
 chmod -x ".devcontainer/devcontainer.json"
 chmod -x ".devcontainer/docker-compose.override.yml"
 chmod -x ".devcontainer/docker-compose.yml"
 chmod -x ".github/workflows/README.md"
 chmod -x ".github/workflows/ci-dotfiles.yml"
 chmod -x ".github/workflows/test-dotfiles.yml"
 chmod -x ".pre-commit-config.yaml"
 chmod -x "README.md"
 chmod -x "admin/licenses.md"
 chmod -x "docs/SSH_KEY_CONFIGURATION.md"
 chmod -x "home/.chezmoi.toml.tmpl"
 chmod -x "home/.chezmoiexternal.toml"
 chmod -x "home/.chezmoiexternals/.keep"
 chmod -x "home/.chezmoiignore.tmpl"
 chmod -x "home/.chezmoiremove"
 chmod -x "home/.chezmoiscripts/run_after_sync-firefox-profile.ps1.tmpl"
 chmod -x "home/.chezmoiscripts/run_after_sync-firefox-profile.sh.tmpl"
 chmod -x "home/.chezmoiscripts/run_after_update-known-hosts.sh.tmpl"
 chmod -x "home/.chezmoiscripts/run_after_validate-ssh-security.ps1.tmpl"
 chmod -x "home/.chezmoiscripts/run_after_validate-ssh-security.sh.tmpl"
 chmod -x "home/.chezmoiscripts/run_once_after_install-packages.ps1.tmpl"
 chmod -x "home/.chezmoiscripts/run_once_after_install-packages.sh.tmpl"
 chmod -x "home/.chezmoiscripts/run_once_after_patch-ssh-config.sh.tmpl"
 chmod -x "home/.chezmoiscripts/run_once_after_switch-default-shell-to-zsh.sh.tmpl"
 chmod -x "home/.chezmoiscripts/run_once_before_generate-ssh-keys.ps1.tmpl"
 chmod -x "home/.chezmoiscripts/run_once_before_generate-ssh-keys.sh.tmpl"
 chmod -x "home/.chezmoiscripts/run_once_fix-ssh-permissions.sh.tmpl"
 chmod -x "home/.chezmoitemplates/browser/chrome/Bookmarks.tmpl"
 chmod -x "home/.chezmoitemplates/browser/chrome/Preferences.tmpl"
 chmod -x "home/.chezmoitemplates/dot_chezmoiignore.tmpl"
 chmod -x "home/.chezmoitemplates/dot_codeium/windsurf/mcp_config.json.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/general-ai/ai-chat-prompt.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/general-ai/markdown-notes.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/software-dev/frontend-dev/css-essentials.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/software-dev/frontend-dev/frontend-node.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/software-dev/general/ai-interaction.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/software-dev/general/feature-flagging-code.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/software-dev/general/feature-matrix.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/software-dev/general/software-development.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/software-dev/meta/new-ruleset.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/software-dev/meta/organize-docs.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/software-dev/platforms/build/makefile-essentials.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/software-dev/platforms/node-dev/typescript-essentials.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/rules/table-of-contents.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/workflows/general/chore-ai20-vcs.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/workflows/software-dev/greenfield/greenfield-prd.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/workflows/software-dev/tasks/prd-to-tasks.md"
 chmod -x "home/.chezmoitemplates/dot_config/ai/workflows/software-dev/tasks/process-tasks.md"
 chmod -x "home/.chezmoitemplates/dot_config/cursor/mcp.json.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/dot_codeium/windsurf/mcp_config.json.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/npm/npmrc.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/init.lua.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/config/lazy.lua.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/plugins/ai.lua.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/plugins/completion.lua.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/plugins/formatting.lua.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/plugins/git.lua.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/plugins/lsp-format.nvim.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/plugins/lsp.lua.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/plugins/navigation.lua.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/plugins/search.lua.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/plugins/session.lua.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/plugins/terminal.lua.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/plugins/treesitter.lua.tmpl"
 chmod -x "home/.chezmoitemplates/dot_config/nvim/lua/plugins/ui.lua.tmpl"
 chmod -x "home/.chezmoitemplates/modify/universal_chrome_preferences.tmpl"
 chmod -x "home/.chezmoitemplates/modify/universal_firefox_user.tmpl"
 chmod -x "home/.chezmoitemplates/modify_dot_ssh/config.tmpl"
 chmod -x "home/.chezmoitemplates/universal_firefox_user.tmpl"
 chmod -x "home/AppData/Local/BraveSoftware/Brave-Browser/User Data/Default/Bookmarks.tmpl"
 chmod -x "home/AppData/Local/BraveSoftware/Brave-Browser/User Data/Default/Preferences.tmpl"
 chmod -x "home/AppData/Local/Chromium/User Data/Default/Bookmarks.tmpl"
 chmod -x "home/AppData/Local/Chromium/User Data/Default/Preferences.tmpl"
 chmod -x "home/AppData/Local/Google/Chrome Beta/User Data/Default/Bookmarks.tmpl"
 chmod -x "home/AppData/Local/Google/Chrome Beta/User Data/Default/Preferences.tmpl"
 chmod -x "home/AppData/Local/Google/Chrome Beta/User Data/Default/modify_AppData_Local_Google_Chrome_Beta_User_Data_Default_Preferences.tmpl"
 chmod -x "home/AppData/Local/Google/Chrome SxS/User Data/Default/Bookmarks.tmpl"
 chmod -x "home/AppData/Local/Google/Chrome SxS/User Data/Default/Preferences.tmpl"
 chmod -x "home/AppData/Local/Google/Chrome for Testing/User Data/Default/Bookmarks.tmpl"
 chmod -x "home/AppData/Local/Google/Chrome for Testing/User Data/Default/Preferences.tmpl"
 chmod -x "home/AppData/Local/Google/Chrome/User Data/Default/Bookmarks.tmpl"
 chmod -x "home/AppData/Local/Google/Chrome/User Data/Default/Preferences.tmpl"
 chmod -x "home/AppData/Local/Google/Chrome/User Data/Default/modify_AppData_Local_Google_Chrome_User_Data_Default_Preferences.tmpl"
 chmod -x "home/AppData/Local/Microsoft/Edge/User Data/Default/Bookmarks.tmpl"
 chmod -x "home/AppData/Local/Microsoft/Edge/User Data/Default/Preferences.tmpl"
 chmod -x "home/AppData/Local/Vivaldi/User Data/Default/Bookmarks.tmpl"
 chmod -x "home/AppData/Local/Vivaldi/User Data/Default/Preferences.tmpl"
 chmod -x "home/AppData/Local/nvim/init.lua.tmpl"
 chmod -x "home/AppData/Local/nvim/lua/config/lazy.lua.tmpl"
 chmod -x "home/AppData/Local/nvim/lua/plugins/lsp.lua.tmpl"
 chmod -x "home/AppData/Roaming/Cursor/mcp.json.tmpl"
 chmod -x "home/AppData/Roaming/Kiro/User/settings.json"
 chmod -x "home/AppData/Roaming/Opera Software/Opera GX Stable/Bookmarks.tmpl"
 chmod -x "home/AppData/Roaming/Opera Software/Opera GX Stable/Preferences.tmpl"
 chmod -x "home/AppData/Roaming/Opera Software/Opera Stable/Bookmarks.tmpl"
 chmod -x "home/AppData/Roaming/Opera Software/Opera Stable/Preferences.tmpl"
 chmod -x "home/AppData/Roaming/Windsurf/mcp_config.json.tmpl"
 chmod -x "home/Library/Application Support/BraveSoftware/Brave-Browser/Default/Bookmarks.tmpl"
 chmod -x "home/Library/Application Support/BraveSoftware/Brave-Browser/Default/Preferences.tmpl"
 chmod -x "home/Library/Application Support/Chromium/Default/Bookmarks.tmpl"
 chmod -x "home/Library/Application Support/Chromium/Default/Preferences.tmpl"
 chmod -x "home/Library/Application Support/Cursor/mcp.json.tmpl"
 chmod -x "home/Library/Application Support/Google/Chrome Beta/Default/Bookmarks.tmpl"
 chmod -x "home/Library/Application Support/Google/Chrome Beta/Default/Preferences.tmpl"
 chmod -x "home/Library/Application Support/Google/Chrome Canary/Default/Bookmarks.tmpl"
 chmod -x "home/Library/Application Support/Google/Chrome Canary/Default/Preferences.tmpl"
 chmod -x "home/Library/Application Support/Google/Chrome for Testing/Default/Bookmarks.tmpl"
 chmod -x "home/Library/Application Support/Google/Chrome for Testing/Default/Preferences.tmpl"
 chmod -x "home/Library/Application Support/Google/Chrome/Default/Bookmarks.tmpl"
 chmod -x "home/Library/Application Support/Google/Chrome/Default/Preferences.tmpl"
 chmod -x "home/Library/Application Support/Microsoft Edge/Default/Bookmarks.tmpl"
 chmod -x "home/Library/Application Support/Microsoft Edge/Default/Preferences.tmpl"
 chmod -x "home/Library/Application Support/Opera GX/Default/Bookmarks.tmpl"
 chmod -x "home/Library/Application Support/Opera GX/Default/Preferences.tmpl"
 chmod -x "home/Library/Application Support/Opera/Default/Bookmarks.tmpl"
 chmod -x "home/Library/Application Support/Opera/Default/Preferences.tmpl"
 chmod -x "home/Library/Application Support/Vivaldi/Default/Bookmarks.tmpl"
 chmod -x "home/Library/Application Support/Vivaldi/Default/Preferences.tmpl"
 chmod -x "home/Library/Application Support/espanso/config/default.yml"
 chmod -x "home/Library/Application Support/espanso/match/base.yml"
 chmod -x "home/Library/Application Support/espanso/match/lorem.yml"
 chmod -x "home/Library/Application Support/espanso/match/misspellings.yml"
 chmod -x "home/Library/Application Support/espanso/match/personal.yml"
 chmod -x "home/dot_ackrc"
 chmod -x "home/dot_bash_env"
 chmod -x "home/dot_bash_login"
 chmod -x "home/dot_bash_profile"
 chmod -x "home/dot_chezmoidata.yaml.tmpl"
 chmod -x "home/dot_claude-code-router/config.json"
 chmod -x "home/dot_codeium/windsurf-next/global_workflows/chore-ai20-vcs.md.tmpl"
 chmod -x "home/dot_codeium/windsurf-next/global_workflows/tasks-prd10-process.md.tmpl"
 chmod -x "home/dot_codeium/windsurf-next/global_workflows/tasks-prd20-from-prd.md.tmpl"
 chmod -x "home/dot_codeium/windsurf-next/global_workflows/tasks-prd30-greenfield.tmpl"
 chmod -x "home/dot_codeium/windsurf-next/mcp_config.json.tmpl"
 chmod -x "home/dot_codeium/windsurf-next/memories/ai-chat-prompt.md.tmpl"
 chmod -x "home/dot_codeium/windsurf-next/memories/global_rules.md.tmpl"
 chmod -x "home/dot_codeium/windsurf-next/memories/markdown-notes.md.tmpl"
 chmod -x "home/dot_codeium/windsurf/global_workflows/_partials/chore-ai20-vcs.md"
 chmod -x "home/dot_codeium/windsurf/global_workflows/_partials/greenfield-prd.md"
 chmod -x "home/dot_codeium/windsurf/global_workflows/_partials/prd-to-tasks.md"
 chmod -x "home/dot_codeium/windsurf/global_workflows/_partials/process-tasks.md"
 chmod -x "home/dot_codeium/windsurf/global_workflows/chore-ai20-vcs.md.tmpl"
 chmod -x "home/dot_codeium/windsurf/global_workflows/greenfield-prd.md.tmpl"
 chmod -x "home/dot_codeium/windsurf/global_workflows/prd-to-tasks.md.tmpl"
 chmod -x "home/dot_codeium/windsurf/global_workflows/process-tasks.md.tmpl"
 chmod -x "home/dot_codeium/windsurf/mcp_config.json.tmpl"
 chmod -x "home/dot_codeium/windsurf/windsurf/rules/ai-chat-prompt.md.tmpl"
 chmod -x "home/dot_codeium/windsurf/windsurf/rules/global_rules.md.tmpl"
 chmod -x "home/dot_codeium/windsurf/windsurf/rules/markdown-notes.md.tmpl"
 chmod -x "home/dot_config/BraveSoftware/Brave-Browser/Default/Bookmarks.tmpl"
 chmod -x "home/dot_config/BraveSoftware/Brave-Browser/Default/Preferences.tmpl"
 chmod -x "home/dot_config/BraveSoftware/Brave-Browser/Default/modify_dot_config_BraveSoftware_Brave-Browser_Default_Preferences.tmpl"
 chmod -x "home/dot_config/Code/User/modify_dot_config_Code_User_settings.json.tmpl"
 chmod -x "home/dot_config/atuin/config.toml.tmpl"
 chmod -x "home/dot_config/bin/docker-all-update/containers-ignore.txt"
 chmod -x "home/dot_config/bin/docker-all-update/images-ignore.txt"
 chmod -x "home/dot_config/browsers/shared-settings.js"
 chmod -x "home/dot_config/chromium/Default/Bookmarks.tmpl"
 chmod -x "home/dot_config/chromium/Default/Preferences.tmpl"
 chmod -x "home/dot_config/chromium/Default/modify_dot_config_chromium_Default_Preferences.tmpl"
 chmod -x "home/dot_config/ctags/base.ctags"
 chmod -x "home/dot_config/ctags/systems-languages.ctags"
 chmod -x "home/dot_config/ctags/web-languages.ctags"
 chmod -x "home/dot_config/curl/config"
 chmod -x "home/dot_config/cursor/mcp.json.tmpl"
 chmod -x "home/dot_config/dot_codeium/windsurf/mcp_config.json.tmpl"
 chmod -x "home/dot_config/filelists/README.md"
 chmod -x "home/dot_config/filelists/ai.ignorefile"
 chmod -x "home/dot_config/filelists/ai.ignorefile.md"
 chmod -x "home/dot_config/filelists/binary.ignorefile"
 chmod -x "home/dot_config/filelists/packaging.ignorefile"
 chmod -x "home/dot_config/filelists/packaging.ignorefile.md"
 chmod -x "home/dot_config/filelists/security.ignorefile"
 chmod -x "home/dot_config/filelists/security.ignorefile.md"
 chmod -x "home/dot_config/filelists/vcs.ignorefile"
 chmod -x "home/dot_config/filelists/vcs.ignorefile.md"
 chmod -x "home/dot_config/firefox-profile-template/addons.json.tmpl"
 chmod -x "home/dot_config/firefox-profile-template/extensions.json.tmpl"
 chmod -x "home/dot_config/firefox-profile-template/handlers.json.tmpl"
 chmod -x "home/dot_config/firefox-profile-template/mimeTypes.rdf.tmpl"
 chmod -x "home/dot_config/firefox-profile-template/modify_dot_config_firefox-profile-template_user.js.tmpl"
 chmod -x "home/dot_config/firefox-profile-template/modify_universal_firefox_user.tmpl.disabled"
 chmod -x "home/dot_config/firefox-profile-template/prefs.js.tmpl"
 chmod -x "home/dot_config/firefox-profile-template/user.js.tmpl"
 chmod -x "home/dot_config/git/commit-template.md"
 chmod -x "home/dot_config/git/config"
 chmod -x "home/dot_config/git/dot_gitconfig.bak"
 chmod -x "home/dot_config/git/dot_gitglobalignore"
 chmod -x "home/dot_config/git/git-automation.md"
 chmod -x "home/dot_config/git/gitattributes"
 chmod -x "home/dot_config/git/globalignore"
 chmod -x "home/dot_config/git/public-vcs.toml"
 chmod -x "home/dot_config/git/sub-config/aliases.gitconfig"
 chmod -x "home/dot_config/git/sub-config/core.gitconfig"
 chmod -x "home/dot_config/git/sub-config/diff-merge.gitconfig"
 chmod -x "home/dot_config/google-chrome-beta/Default/Bookmarks.tmpl"
 chmod -x "home/dot_config/google-chrome-beta/Default/Preferences.tmpl"
 chmod -x "home/dot_config/google-chrome-beta/Default/modify_dot_config_google-chrome-beta_Default_Preferences.tmpl"
 chmod -x "home/dot_config/google-chrome-for-testing/Default/Bookmarks.tmpl"
 chmod -x "home/dot_config/google-chrome-for-testing/Default/Preferences.tmpl"
 chmod -x "home/dot_config/google-chrome-for-testing/Default/modify_dot_config_google-chrome-for-testing_Default_Preferences.tmpl"
 chmod -x "home/dot_config/google-chrome-unstable/Default/Bookmarks.tmpl"
 chmod -x "home/dot_config/google-chrome-unstable/Default/Preferences.tmpl"
 chmod -x "home/dot_config/google-chrome-unstable/Default/modify_dot_config_google-chrome-unstable_Default_Preferences.tmpl"
 chmod -x "home/dot_config/google-chrome/Default/Bookmarks.tmpl"
 chmod -x "home/dot_config/google-chrome/Default/Preferences.tmpl"
 chmod -x "home/dot_config/google-chrome/Default/modify_dot_config_google-chrome_Default_Preferences.tmpl"
 chmod -x "home/dot_config/microsoft-edge/Default/Bookmarks.tmpl"
 chmod -x "home/dot_config/microsoft-edge/Default/Preferences.tmpl"
 chmod -x "home/dot_config/microsoft-edge/Default/modify_dot_config_microsoft-edge_Default_Preferences.tmpl"
 chmod -x "home/dot_config/mise/mise.toml"
 chmod -x "home/dot_config/nano/config"
 chmod -x "home/dot_config/npm/npmrc.tmpl"
 chmod -x "home/dot_config/nvim/init.lua.tmpl"
 chmod -x "home/dot_config/nvim/lua/config/lazy.lua.tmpl"
 chmod -x "home/dot_config/nvim/lua/config/plugins/lsp.lua.tmpl"
 chmod -x "home/dot_config/opera-gx/Default/Bookmarks.tmpl"
 chmod -x "home/dot_config/opera-gx/Default/Preferences.tmpl"
 chmod -x "home/dot_config/opera/Default/Bookmarks.tmpl"
 chmod -x "home/dot_config/opera/Default/Preferences.tmpl"
 chmod -x "home/dot_config/pnpm/rc.tmpl"
 chmod -x "home/dot_config/psql/psqlrc"
 chmod -x "home/dot_config/psql/psqlrc-alias"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/activity.sql"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/autovac_runtime.sql"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/dbsize.sql"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/enums.sql"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/largest_objects.sql"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/last_vacuum_analyze.sql"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/locks.sql"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/rtsize.sql"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/tablesize.sql"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/tsize.sql"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/uselesscol.sql"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/vac_ready.sql"
 chmod -x "home/dot_config/psql/psqlrc-aliases/admin/waits.sql"
 chmod -x "home/dot_config/ripgrep/config"
 chmod -x "home/dot_config/ripgrep/ripgrepignore"
 chmod -x "home/dot_config/shells/README.md"
 chmod -x "home/dot_config/shells/bash/README.md"
 chmod -x "home/dot_config/shells/bash/dot_bashrc"
 chmod -x "home/dot_config/shells/bash/env/README.md"
 chmod -x "home/dot_config/shells/shared/README.md"
 chmod -x "home/dot_config/shells/shared/aliases/README.md"
 chmod -x "home/dot_config/shells/shared/env/README.md"
 chmod -x "home/dot_config/shells/shared/env/modern-tool-map.ini"
 chmod -x "home/dot_config/shells/shared/env/shared-env.cfg"
 chmod -x "home/dot_config/shells/shared/util/README.md"
 chmod -x "home/dot_config/shells/zsh/README.md"
 chmod -x "home/dot_config/shells/zsh/dot_zlogin"
 chmod -x "home/dot_config/shells/zsh/dot_zprofile"
 chmod -x "home/dot_config/shells/zsh/dot_zshrc"
 chmod -x "home/dot_config/shells/zsh/env/README.md"
 chmod -x "home/dot_config/tealdeer/config.toml"
 chmod -x "home/dot_config/templates/dot_github/ISSUE_TEMPLATE/config.yml"
 chmod -x "home/dot_config/templates/dot_github/README.md"
 chmod -x "home/dot_config/terminal-jarvis/config.toml.tmpl"
 chmod -x "home/dot_config/vivaldi/Default/Bookmarks.tmpl"
 chmod -x "home/dot_config/vivaldi/Default/Preferences.tmpl"
 chmod -x "home/dot_config/vivaldi/Default/modify_dot_config_vivaldi_Default_Preferences.tmpl"
 chmod -x "home/dot_config/yamllint/config"
 chmod -x "home/dot_ctags"
 chmod -x "home/dot_editorconfig"
 chmod -x "home/dot_editorconfig-checker.json"
 chmod -x "home/dot_golangci.yml"
 chmod -x "home/dot_librewolf/librewolf.overrides.cfg.tmpl"
 chmod -x "home/dot_local/bin/DebugWindowsNetworkMTU.ps1"
 chmod -x "home/dot_local/bin/docker-all-update.md"
 chmod -x "home/dot_local/share/git/public-vcs.example.toml"
 chmod -x "home/dot_m2/settings.xml-example"
 chmod -x "home/dot_markdownlint-cli2.yaml"
 chmod -x "home/dot_mvn/extensions.xml"
 chmod -x "home/dot_mvn/jvm.config"
 chmod -x "home/dot_mvn/maven.config"
 chmod -x "home/dot_profile"
 chmod -x "home/dot_ssh/modify_dot_ssh_config.tmpl"
 chmod -x "home/dot_tmux.conf"
 chmod -x "home/dot_yarnrc.yml"
 chmod -x "home/dot_zshenv"
 chmod -x "internal-docs/requirements/README.md"
 chmod -x "internal-docs/requirements/git-configuration.feature"
 chmod -x "internal-docs/requirements/performance.feature"
 chmod -x "internal-docs/requirements/shell-configuration.feature"
 chmod -x "internal-docs/requirements/shell-tests.feature"
 chmod -x "internal-docs/requirements/steps/README.md"
 chmod -x "internal-docs/requirements/steps/dotfiles-migration-checklist.md"
 chmod -x "internal-docs/specs/202508131000improvements/tasks.md"
 chmod -x "remote-dev/.devcontainer/devcontainer.json"
 chmod -x "remote-dev/containers/debian-gui/Dockerfile"
 chmod -x "remote-dev/containers/debian-gui/supervisord.conf"
 chmod -x "remote-dev/docker-compose.yml"

