#!/usr/bin/env zsh

# startup order is zshenv zprofile zshrc zlogin
# zprofile and zlogin are only for login shells
# non-interactive shells only source zshenv

#------------------------------------------------------------------------------
# OhMyZsh Plugin Manager
#------------------------------------------------------------------------------
export ZSH="$HOME/.oh-my-zsh"
ZSH_THEME="robbyrussell"
plugins=(git)
source $ZSH/oh-my-zsh.sh

if [[ ! -f ~/.p10k.zsh ]]; then
  echo "Installing Powerlevel10k..."
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.config/zsh/plugins/powerlevel10k
  echo 'source ~/.config/zsh/plugins/powerlevel10k/powerlevel10k.zsh' >>! ~/.zshrc
fi

# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block, everything else may go below.
if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
fi

#------------------------------------------------------------------------------
# Zinit Plugins
#------------------------------------------------------------------------------
#if [[ ! -f ~/.zinit/bin/zinit.zsh ]]; then
#    print "Installing zinit..."
#    sh -c "$(curl -fsSL https://git.io/Jv1OO)"
#fi

#source ~/.zinit/bin/zinit.zsh

# zinit light zsh-users/zsh-autosuggestions
# zinit light zsh-users/zsh-syntax-highlighting

#------------------------------------------------------------------------------
# Source Zsh Entrypoint (universal + Zsh-specific logic)
#------------------------------------------------------------------------------
if [[ -r ~/.config/shells/zsh/entrypoint.zsh ]]; then
    source ~/.config/shells/zsh/entrypoint.zsh
fi

# Source Powerlevel10k
if [[ -r ~/.config/zsh/plugins/powerlevel10k/powerlevel10k.zsh ]]; then
    source ~/.config/zsh/plugins/powerlevel10k/powerlevel10k.zsh
fi

#------------------------------------------------------------------------------
# iff NOT using PowerLevel10k: Load Starship Prompt (Moved here for faster startup)
#------------------------------------------------------------------------------
#eval "$(starship init zsh)"

