[".local/share/zsh/completions/_eza"]
    refreshPeriod = "168h"
    type          = "file"
    url           = "https://raw.githubusercontent.com/eza-community/eza/main/completions/zsh/_eza"

[".agent-os"]
    type = "git-repo"
    url = "https://github.com/levonk/agent-os"
    ref = "levonk"  # or a specific tag/commit hash
    refreshPeriod = "24h"  # optional: weekly refresh
    preforkurl = "https://github.com/buildermethods/agent-os"
    project-docs = "https://buildermethods.com/agent-os"

# Managed by chezmoi: externals to fetch on apply
# Powerlevel10k installed where Oh My Zsh expects themes
[".config/shells/zsh/custom/themes/powerlevel10k"]
    type = "git-repo"
    url = "https://github.com/levonk/powerlevel10k.git"
    refreshPeriod = "168h"
    exact = true

[".config/shells/zsh/custom/themes/powerlevel10k".clone]
    args = ["--depth=1"]

[".config/shells/zsh/oh-my-zsh"]
    type = "git-repo"
    url  = "https://github.com/levonk/ohmyzsh.git"
    ref = "levonk"  # or a specific tag/commit hash
    refreshPeriod = "168h"
