#!/usr/bin/env zsh

# startup order is zshenv zprofile zshrc zlogin
# zprofile and zlogin are only for login shells
# non-interactive shells only source zshenv

#------------------------------------------------------------------------------
# OhMyZsh Plugin Manager
#------------------------------------------------------------------------------
if [[ ! -f ~/.p10k.zsh ]]; then
  echo "Installing Powerlevel10k..."
  git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.config/zsh/plugins/powerlevel10k
  echo 'source ~/.config/zsh/plugins/powerlevel10k/powerlevel10k.zsh' >>! ~/.zshrc
fi

# Source Powerlevel10k
if [[ -r ~/.config/zsh/plugins/powerlevel10k/powerlevel10k.zsh ]]; then
    source ~/.config/zsh/plugins/powerlevel10k/powerlevel10k.zsh
fi

#------------------------------------------------------------------------------
# Zinit Plugins
#------------------------------------------------------------------------------
#if [[ ! -f ~/.zinit/bin/zinit.zsh ]]; then
#    print "Installing zinit..."
#    sh -c "$(curl -fsSL https://git.io/Jv1OO)"
#fi

#source ~/.zinit/bin/zinit.zsh

# zinit light zsh-users/zsh-autosuggestions
# zinit light zsh-users/zsh-syntax-highlighting

#------------------------------------------------------------------------------
# Source Shared Configuration
#------------------------------------------------------------------------------
if [[ -r ~/.config/zsh/sharedrc ]]; then
    source ~/.config/zsh/sharedrc
fi

#------------------------------------------------------------------------------
# iff NOT using PowerLevel10k: Load Starship Prompt (Moved here for faster startup)
#------------------------------------------------------------------------------
#eval "$(starship init zsh)"
