# Docker Compose Override for Development
# This file provides development-specific overrides for the base docker-compose.yml
# It's automatically loaded by Docker Compose when present

version: '3.8'

# Examples for local overrides (uncomment as needed):

# services:
#   dotfiles-test:
#     # Expose ports if needed by a local server
#     # ports:
#     #   - "3000:3000"
#     #   - "8080:8080"
#
#     # Increase resource limits for heavy workloads
#     # deploy:
#     #   resources:
#     #     limits:
#     #       memory: 2G
#     #       cpus: '1.0'
#     #     reservations:
#     #       memory: 512M
#     #       cpus: '0.2'
#
#   # Override options for the Bash test service if necessary
#   # dotfiles-bash-test:
#   #   ports:
#   #     - "2222:22"
#
# volumes:
#   # Optional: Additional volumes for development
#   # extra-cache:
#   #   driver: local
